### ISSUE TITLE
Archive 1.0 Tracking Issue

### ISSUE THREAD

**Issue by insipx** [paritytech/substrate-archive#303]
- [ ] Integration with Desub
  - [ ] Desub should seek some kind of integration with the upcoming scale-info changes
      - [ ] Desub needs to be updated to the latest types/metadata
  - [ ] Actor for type-decoding
  - [ ] storage schema for type-decoding
  - [ ] rel #159 #132 #26
- [ ] Parity Db Support #76 
- [ ] Filtering based on types/pallets/storage keys #97 / #136 

## Bug Fixes needed:
- [ ] Handle Forked Blocks Bug (#229) 
- [ ] Fix 'Tasks Timed Out' bug

## Nice to Have:
- [ ] More Unit tests
    - [ ] Unit tests for each actor
    - [ ] Unit tests for each query
- [ ] General Integration tests for archive in general
    - [ ] Integration tests for Polkadot/Kusama

**Comment by xcaptain** [comment]
What's the status of 
> Actor for type-decoding
> storage schema for type-decoding

Since https://github.com/paritytech/substrate-archive/pull/394 was merged.

**Comment by insipx** [comment]
@xcaptain 

There's an actor to decode extrinsics and it works, with some caveats:

- there may be discrepencies between the formats of newer, scale-info-produced JSON and legacy-desub produced JSON (in terms of extrinsics)
- once archive reaches the point at which it begins to decode extrinsics using `desub-current`, i.e. `scale-info` the memory tends to balloon. This could/is for a few reasons and there could be optimizations made in archive, but imo mainly because of the presence of doc-strings within the metadata (which take up a most of the extrinsic in scale-info). If we are decoding 1000-10,000 extrinsics at once, this causes significant memory issues


Other than this, indexing is fast enough and it works
